// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6JAqhuD4koVKCOFbVVBW7kD8MJxvw6jU',
    appId: '1:405687784887:web:e873d662e69fd4be7ac432',
    messagingSenderId: '405687784887',
    projectId: 'alam-fabrics',
    authDomain: 'alam-fabrics.firebaseapp.com',
    storageBucket: 'alam-fabrics.firebasestorage.app',
    measurementId: 'G-CRMD233JQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05BQrUbjYna5mxELnd8E6EqQ_UJokKns',
    appId: '1:405687784887:android:5116ec3bbeb905f67ac432',
    messagingSenderId: '405687784887',
    projectId: 'alam-fabrics',
    storageBucket: 'alam-fabrics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8n3HRbeWyeMJsjWJsShSmDMptPQu2fxA',
    appId: '1:405687784887:ios:2c075f058b3f1cb17ac432',
    messagingSenderId: '405687784887',
    projectId: 'alam-fabrics',
    storageBucket: 'alam-fabrics.firebasestorage.app',
    iosBundleId: 'com.example.alamFabrics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8n3HRbeWyeMJsjWJsShSmDMptPQu2fxA',
    appId: '1:405687784887:ios:2c075f058b3f1cb17ac432',
    messagingSenderId: '405687784887',
    projectId: 'alam-fabrics',
    storageBucket: 'alam-fabrics.firebasestorage.app',
    iosBundleId: 'com.example.alamFabrics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6JAqhuD4koVKCOFbVVBW7kD8MJxvw6jU',
    appId: '1:405687784887:web:eed162e0c86455147ac432',
    messagingSenderId: '405687784887',
    projectId: 'alam-fabrics',
    authDomain: 'alam-fabrics.firebaseapp.com',
    storageBucket: 'alam-fabrics.firebasestorage.app',
    measurementId: 'G-M7GSHL7VX4',
  );
}
